### ISSUE TITLE
Omroep Brabant TV vs Omroep Brabant

### ISSUE THREAD

**Issue by schumi2004** [Stevie-v/srp.220x132.transparent-white-ziggo#2]
Stevie-v,

Can you make a copy from 1_0_1_4C89_83B_600_FFFF0000_0_0_0.png (Omroep Brabant) to 1_0_1_4D70_BBC_600_FFFF0000_0_0_0.png (Omroep Brabant TV) ?
It's the same channel except Omroep Brabant TV is missing the logo.

Thanks in advance.

**Comment by Stevie-v** [comment]
I am on holiday now when i am back i will look at it.

**Comment by schumi2004** [comment]
@Stevie-v 
Enjoy your vacation and stay of the internet ;)
Have fun !

**Comment by schumi2004** [comment]
Al tijd gehad om ernaar te kijken?

**Comment by Stevie-v** [comment]
Hier heeft omroep Brabant een andere zenderreferentie dan bij jou blijkbaar.
Ik ga enkel uit van mij zenderlijst, dit is toch binnen een handomdraai te fixen door die picon even te renamen of begrijp ik je verkeerd?

**Comment by schumi2004** [comment]
Ik denk dat we mekaar verkeerd begrijpen.
Ik kan inderdaad eenvoudig van 1_0_1_4C89_83B_600_FFFF0000_0_0_0.png  (Omroep Brabant) een kopie maken naar 1_0_1_4D70_BBC_600_FFFF0000_0_0_0.png (Omroep Brabant TV)  wat schijnbaar het HD equivalent moet voorstellen van Omroep Brabant, deze is er nu namelijk niet. (het is niet een kwestie van renamen)

Ik begrijp ook dat je je eigen zenderlijst hanteert en tot dus ver komen alle zenders ook netjes overeen echter deze is er niet (ook niet onder een andere naam).
beetje vergelijkbaar met Ziggo logo wat ook meerdere keren hetzelfde maar dan met andere filenaam voorkomt (1_0_1_4C85_83B_600_FFFF0000_0_0_0.png)

**Comment by Stevie-v** [comment]
Ik begrijp je niet helemaal, het logo van omroep Brabant is anders dan van omroep Brabant tv?
Misschien dat ik dit logo dan kan plaatsen op request?

**Comment by Stevie-v** [comment]
![logo](https://user-images.githubusercontent.com/25457350/33486619-0e9e755e-d6ab-11e7-8122-b0db83da9ec1.png)

**Comment by schumi2004** [comment]
Nee logo's zijn het zelfde net zoals die default Ziggo logo's voor verschillende zenderfrequenties hetzelfde zijn.
En met die gedachte (meerdere keren zelfde Ziggo logo) had ik dit issue gemaakt omdat er 1 logo/zenderfrequentie mist voor Omroep Brabant.
En gezien de nummering in zenderoverzicht doe ik een aanname dat zender 30 in mijn geval de HD variant moet voorstellen.

**Comment by Stevie-v** [comment]
Is dit wat de bedoeling is?

**Comment by schumi2004** [comment]
Onze comments hebben elkaar net gekruist en ik denk dat het daar nu duidelijker mee wordt wat ik bedoelde. Dit logo ziet er wel beter uit als huidige OB logo trouwens ;)

**Comment by Stevie-v** [comment]
Ik heb wel twee logo`s van Out tv erin zitten en twee logo`s van L1 Limburg, misschien is jou zenderlijst dan anders?
Ik zie in mijn zenderlijst geen dubbele omroep Brabant staan?

**Comment by schumi2004** [comment]
Als jij geen dubbele ziet dan is mijn lijst anders en snap ik de verwarring.
Ik heb er 1 op 30 (Die met TV in titel) en 1 op 732 uit mijn hoofd en dan nog een Radio kanaal, 3 in totaal dus.
Ik maak anders wel gewoon een nieuw logo aan met die je hier gepost heb is het ook opgelost ;)
