### ISSUE TITLE
Ziggo Sport Docu en Ziggo Sport Extra HD - iconen werken niet

### ISSUE THREAD

**Issue by francoism90** [Stevie-v/srp.220x132.transparent-white-ziggo#5]
Weetniet of het ligt aan mijn setup, dit zijn de icoon-locaties volgens TVHeadend:
`picon://1_0_1_4B37_810_600_FFFF0000_0_0_0.png` => Ziggo Sport Docu HD
`picon://1_0_1_4B38_810_600_FFFF0000_0_0_0.png` => Ziggo Sport Extra HD

De rest van de iconen werken allemaal, echter deze niet.

Bedankt voor het maken van dit thema!

**Comment by Stevie-v** [comment]
Hier werken ze prima dus ik denk dat in jou regio de zenderreferenties van deze twee zenders dan anders zijn, ik heb het net gecontroleerd.
Zelf even aanpassen deze twee zenders is dan ook mijn advies, laat even weten welke zenderreferenties deze twee zenders bij jou hebben?
MvG Stefan

**Comment by francoism90** [comment]
Wat bedoel je precies met de zenderreferenties? Welke informatie heb je nodig? :)

**Comment by Stevie-v** [comment]
De locaties zoals je in je eerste bericht al aangeeft, de cijfer combinatie 1_0_1 en dan wat volgt?

**Comment by francoism90** [comment]
Hmm, staat dit nog niet in het eerste bericht?
Ik heb gezocht, maar dit is het enige wat ik bv. zie: `4B38_810_600_FFFF0000_0_0_0`.

Ik kan ook de locatie inderdaad aanpassen als in deze commit: https://github.com/Stevie-v/srp.220x132.transparent-white-ziggo/commit/a801d5dc57de145a2753e4a8a6ad6a5bd7603116

Hmm, deze zijn zonder HD in het logo, kan het daar aan liggen?

**Comment by Stevie-v** [comment]
Het moet 1_0_19 zijn aangezien het HD zenders zijn en dus niet 1_0_1 zoals ze bij jou staan.
Op de Git staat ze gewoon goed dus de fout moet ergens bij jou zitten.

**Comment by francoism90** [comment]
@Stevie-v Bedankt voor het nakijken! Heb het handmatig aangepast naar `1_0_19`.
